 select top 10 * from [dbo].[clean_dataset.csv]

--Q1. what is total revenue generated by male vs female customers?

 select gender,sum(purchase_amount_usd) as revenue 
 from [dbo].[clean_dataset.csv]
 group by gender
--here we see revenue genrated by male is more than females

--Q2. which customer used a discount but stil spent more than the average purchase amount?

select customer_id,purchase_amount_usd from [dbo].[clean_dataset.csv]
where discount_applied='Yes' and 
purchase_amount_usd>=(select AVG(purchase_amount_usd) from [dbo].[clean_dataset.csv])

--Q3. which are the top 5 products with the highest average review rating

select top 5 item_purchased, ROUND(AVG(review_rating),2) from [dbo].[clean_dataset.csv]
group by item_purchased
order by AVG(review_rating) desc

--Q4. Compare the average purchase amount between standard and  express shipping

select shipping_type, AVG(purchase_amount_usd) from [dbo].[clean_dataset.csv]
where shipping_type in ('Express','Standard')
group by shipping_type
order by AVG(purchase_amount_usd) desc

--Q5. Do subscribe customer spend more? compare average spend and total revenue between subscriber and non-subscriber


select subscription_status, COUNT(customer_id) as total_customer , 
SUM(purchase_amount_usd) as total_revenue, AVG(purchase_amount_usd) as avg_spend
from [dbo].[clean_dataset.csv]
group by subscription_status
order by SUM(purchase_amount_usd) desc

--Q6. which products have the highest percentage of purchase with dicount applied?

select top 5 item_purchased,
ROUND(100*SUM(CASE when discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from [dbo].[clean_dataset.csv]
group by item_purchased
order by discount_rate desc

--Q7. Segment customer into new, Returning and loyal based on their total number of previous purchases and show the count of each segment

with customer_type as (
select customer_id,previous_purchases,
CASE 
WHEN previous_purchases =1 THEN 'New'
WHEN previous_purchases BETWEEN 1 AND 10 THEN 'returning'
ELSE 'Loyal'
END AS Customer_segment
from [dbo].[clean_dataset.csv]
)

select customer_segment, COUNT(*) as 'Number of customer'
from customer_type
group by Customer_segment
order by [Number of customer] desc


--Q8. What are the top 3 most purchased product with each category?
with item_counts as(
select category,item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from [dbo].[clean_dataset.csv]
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

select subscription_status,
COUNT(customer_id) as repeat_buyers
from [dbo].[clean_dataset.csv]
where previous_purchases>5
group by subscription_status

--Q10. what is the revenue contribution of each age group

select age_groups,SUM(purchase_amount_usd) as total_revenue
from [dbo].[clean_dataset.csv]
group by age_groups
order by  total_revenue desc









